declare module 'electron-better-ipc';
declare module '*.svg';
declare module '*.yml';
declare module '*.jpg';
declare module '*.png';
declare module '*.ttf';
declare module '@nicmosc/react-image-palette';
declare module '@react-pdf/renderer';
declare module 'react-pdf/dist/entry.webpack';
