export { default as Cover } from './Cover';
export { default as Profile } from './Profile';
export { default as HowWeWork } from './HowWeWork';
export { default as WhatWeDo } from './WhatWeDo';
export { default as PaymentMethods } from './PaymentMethods';
export { default as Stats } from './Stats';
export { default as Project } from './Project';
export { default as StoryTelling } from './StoryTelling';
export { default as Tables } from './Tables';
